#!/usr/bin/env bash

MYDIR="`dirname $(cd "${0%/*}" 2>/dev/null; echo "$PWD"/"${0##*/}")`"

for i in .ctags .gvimrc .vim .vimrc .vimrc.local .vimrc.bundles; do
    test -e ~/$i || ln -s "$MYDIR/$i" ~/$i
done
